Repository SovereignCloudStack/standards, pull requests merged in 2023-05, with the labels that each got.

#287 add ISSUE templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/standard-user-story.md
Labels: documentation, Community

#286 Add first draft of status page ref implementation decision
  Standards/scs-0401-v1-status-page-reference-implementation-decision.md
Labels: Ops, Sprint Copenhagen

#290 Add links to OpenStack Health Monitors on Stds list.
  README.md
Labels: IaaS, standards

#270 Update ADR on SSO-Identity-Federation
  Standards/scs-0300-v1-requirements-for-sso-identity-federation.md
Labels: IAM, Sprint Copenhagen

#291 Image metadata is an approved std since long. Move.
  Standards/scs-0102-v1-image-metadata.md
  Tests/scs-compatible-test.yaml
  Tests/scs-compatible.yaml
Labels: IaaS, standards, SCS is standardized

#292 Refactor the flavor naming document to make it more readable.
  Standards/scs-0100-v2-flavor-naming.md
Labels: IaaS, standards, SCS is standardized

#293 Call doc v2.1. Backticks were still wrong at one place.
  Standards/scs-0100-v2-flavor-naming.md
Labels: IaaS, standards
