Repository SovereignCloudStack/standards, pull requests merged in 2023-03, with the labels that each got.

#198 Propose to stabilize default storage class scs-0211 by 2023-02-13.
  Standards/scs-0211-v1-kaas-default-storage-class.md
Labels: work in progress, Container, standards

#191 Feat/add status page design decision
  Standards/scs-0400-v1-status-page-create-decision.md
Labels: Ops

#253 V2 version for IaaS compatibility.
  Tests/scs-compatible.yaml
Labels: enhancement, work in progress, standards
