Repository SovereignCloudStack/standards, pull requests merged in 2024-05, with the labels that each got.

#588 Feat/add poc wgcloud
  .github/workflows/check-poc-wgcloud-v3.yml
  README.md
  Tests/iaas/entropy/entropy-check.py
Labels: enhancement, standards, SCS-VP10

#589 Multiline entry for PCO Regions.
  README.md
Labels: enhancement, standards

#584 Keep CPU architecture in short name (if non-x86).
  Tests/iaas/flavor-naming/flavor_names.py
Labels: bug, IaaS, standards

#597 Run unit tests when requirements are updated
  .github/workflows/test-python.yml
Labels: SCS-VP10
