Repository SovereignCloudStack/standards, pull requests merged in 2024-03, with the labels that each got.

#493 Extend VM bootup timeout in entropy test
  Tests/iaas/entropy/entropy-check.py
Labels: SCS is standardized, SCS-VP10

#496 Bugfix: ADR checker didn't exclude proposals from duplicate check
  Tests/chk_adrs.py
Labels: SCS is standardized, SCS-VP10

#484 Add Tests/scs-compatible-kaas.yaml
  Tests/scs-compatible-kaas.yaml
Labels: Container, SCS is standardized, SCS-VP10

#499 Minor editorial improvements to K8s version policy standards scs-0210-v1 and scs-0210-v2
  Standards/scs-0210-v1-k8s-new-version-policy.md
  Standards/scs-0210-v2-k8s-version-policy.md
Labels: SCS is standardized, SCS-VP10

#467 Discussion about obsoleted_at and deprecated_at
  Standards/scs-0001-v1-sovereign-cloud-standards.md
  Standards/scs-0003-v1-sovereign-cloud-standards-yaml.md
  Standards/scs-0100-v1-flavor-naming.md
  Standards/scs-0100-v2-flavor-naming.md
  Standards/scs-0210-v1-k8s-new-version-policy.md
  Tests/chk_adrs.py
  Tests/scs-compatible-iaas.yaml
  Tests/scs-compliance-check.py
  Tests/testing/scs-compatible-test.yaml
Labels: housekeeping, SCS is standardized, SCS-VP10

#513 Add compliance checks for PCO Prod4.
  .github/scs-compliance-check/openstack/clouds.yaml
  .github/workflows/check-pco-prod4-v2.yml
  .github/workflows/check-pco-prod4-v3.yml
  README.md
Labels: enhancement, standards

#516 Feat/rmv iaasv1 add iaasv4
  .github/workflows/check-artcodix-v4.yml
  .github/workflows/check-gx-scs-v4.yml
  .github/workflows/check-pco-prod2-v4.yml
  .github/workflows/check-pco-prod3-v4.yml
  .github/workflows/check-pco-prod4-v4.yml
  .github/workflows/check-regio-a-v4.yml
  .github/workflows/check-wavestack-v4.yml
  README.md
Labels: enhancement, IaaS, standards

#518 Integrate topology.scs.openstack.org/host-id into node distribution test (issues/#540)
  Tests/kaas/k8s-node-distribution/k8s-node-distribution-check.py
Labels: Container, SCS is continuously built and tested, SCS-VP10

#528 Update label in node distribution test (issues/#540)
  Tests/kaas/k8s-node-distribution/k8s-node-distribution-check.py
Labels: Container, SCS is standardized, SCS-VP10

#529 Feat/add aov
  README.md
Labels: enhancement

#532 Fix an AttributeError and misleading log message
  Tests/kaas/k8s-version-policy/k8s_version_policy.py
Labels: SCS-VP10

#523 Rename the Domain Manager role to "manager"
  Standards/scs-0302-v1-domain-manager-role.md
  Tests/iam/domain-manager/README.md
Labels: SCS-VP10

#531 Add unit and regression tests for conformance tests
  .github/workflows/lint-python.yml
  .github/workflows/test-python.yml
  Tests/.coveragerc
  Tests/.gitignore
  Tests/README.md
  Tests/iaas/flavor-naming/check_yaml.py
  Tests/iaas/flavor-naming/check_yaml_test.py
  Tests/kaas/k8s-version-policy/k8s_version_policy.py
  Tests/kaas/k8s-version-policy/k8s_version_policy_test.py
  Tests/kaas/k8s-version-policy/testdata/README.md
  Tests/kaas/k8s-version-policy/testdata/releases.json
  Tests/test-requirements.in
  Tests/test-requirements.txt
  playbooks/adr_syntax.yaml
Labels: SCS-VP10
