Repository SovereignCloudStack/standards, pull requests merged in 2024-07, with the labels that each got.

#661 Add information about conformance check in standard scs-0211-v1
  Standards/scs-0211-v1-kaas-default-storage-class.md
Labels: Container, SCS is standardized, SCS-VP10

#600 Update cert table to use v4 of scs-compatible iaas, for all the older…
  README.md
Labels: SCS is standardized, SCS-VP10

#675 mark dead HM link as broken
  README.md
Labels: SCS-VP10
